name: "isms"
version: "3.9"
services:

  postgres:
    container_name: postgres-isms
    image: postgres:16-alpine
    environment:
      POSRGRES_DB: ismsdatenbank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgresPwd2025
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 10
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.sql
    ports:
      - "5432:5432"
    networks: [ isms ]
networks:
  isms: {}

